### ISSUE TITLE
内容安全接口，图片审核返回Status 412 Precondition Failed

### ISSUE THREAD

**Issue by ahkimkoo** [fastwego/miniprogram#3]
https://pkg.go.dev/github.com/fastwego/miniprogram/apis/security?tab=doc#ImgSecCheck
这个接口返回错误Status 412 Precondition Failed
可能是formdata构造不对，希望能够修改一下，谢谢

**Comment by Ceelog** [comment]
更新了 https://github.com/fastwego/miniprogram/commit/2c6c439b61b9b337409914838302df1e012ef66a
